using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static EJ2GirdBrowserSample.Controllers.DataBindingController;

namespace EJ2Grid.Controllers
{
    public class ColumnsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AutoGeneratedColumns()
        {
            var Order = OrderDetails.GetAllRecords();
            ViewBag.DataSource = Order;
            return View();
        }
        public IActionResult Headers()
        {
            var Emp = OrderDetails.GetAllRecords();
            ViewBag.DataSource = Emp;
            return View();
        }
        public IActionResult ColumnTemplate()
        {
            var Emp = OrderDetails.GetAllRecords();
            ViewBag.DataSource = Emp;
            return View();
        }
        public IActionResult ComplexDataBinding()
        {
            var ComplexData = OrderDetails.GetAllRecords();
            ViewBag.data = ComplexData;
            return View();
        }
        public IActionResult AutoFitColumns()
        {
            var Order = OrderDetails.GetAllRecords();
            ViewBag.DataSource = Order;
            return View();
        }
        public IActionResult ColumnReorder()
        {
            var Emp = OrderDetails.GetAllRecords();
            ViewBag.DataSource = Emp;
            return View();
        }
        public IActionResult ColumnResizing()
        {
            var Emp = OrderDetails.GetAllRecords();
            ViewBag.DataSource = Emp;
            return View();
        }
        public IActionResult ColumnChooser()
        {
            var Emp = OrderDetails.GetAllRecords();
            ViewBag.DataSource = Emp;
            return View();
        }
        public IActionResult ColumnMenu()
        {
            var Emp = OrderDetails.GetAllRecords();
            ViewBag.DataSource = Emp;
            return View();
        }
        public IActionResult ColumnSpanning()
        {
            ViewBag.DataSource = OrderDetails.GetAllRecords();
            return View();
        }
        public IActionResult ResponsiveColumns()
        {
            var Emp = OrderDetails.GetAllRecords();
            ViewBag.DataSource = Emp;
            return View();
        }
    }
}
